name:                toylang
version:             0.0.0.1
license:             "CC BY-NC-ND 4.0"
author:              "Gary Verhaegen"
copyright:           "2020 Gary Verhaegen"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: This project is not meant to be seen. Move along.

dependencies:
- base >= 4.7 && < 5

default-extensions:
- LambdaCase

library:
  source-dirs: src

executables:
  toylang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toylang

tests:
  toylang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toylang
