Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "512"
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y hugs
  SHELL
end
