name:                titans
version:             0.0.0

extra-source-files:
- README.md

description:         Please see the README on GitHub

dependencies:
- base >= 4.7 && < 5
- containers

default-extensions:
- ScopedTypeVariables

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -O2

library:
  source-dirs: src

executables:
  titans-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - titans

tests:
  titans-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - titans
